require 'rubygems'
require 'railsless-deploy'
load 'deploy'
load 'config/deploy' # remove this line to skip loading any of the default tasks
load 'config/deploy.rb' if respond_to?(:namespace)
# Uncomment if you are using Rails' asset pipeline
    # load 'deploy/assets'
